# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

variables:
  buildConfiguration: 'Release'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    includeNuGetOrg: true

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    restoreNugetPackages: true
    clean: true
    configuration: $(buildConfiguration)

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- bash: print "Helloee world from Basher!"
  displayName: 'bash says hello'
